name: Build and Deploy
on:
  push:
    branches:
      - master, dev
  pull_request:
    branches:
      - master, dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: . # Set this to the directory containing your Dockerfile
        file: ./Dockerfile # Specify the path to your Dockerfile
        push: false # Set this to true to push the image

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: github.ref == 'refs/heads/dev' # Only push on master branch
      run: docker push learning:latest # Adjust the tag as needed

    - name: Clean up Docker images
      run: docker system prune -f
