name: Test and Build .NET Project with SQLite

on:
   push:
      branches:
      - master
   pull_request:
      branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Build project
        run: dotnet build

      - name: Install SQLite
        run: sudo apt-get install sqlite3
      - name: Download File
        run: |
           ls -R $GITHUB_WORKSPACE/Learning.Test
           curl -L -o $GITHUB_WORKSPACE/Learning.Test/bin/Debug/net7.0/learning.db https://theraparea-backend-dev.s3.amazonaws.com/learning.db
           ls -R $GITHUB_WORKSPACE/Learning.Test
           #ls -R Learning.Test/bin/Debug/net7.0
           #ls -R Learning.Test/bin/Release/net7.0
           #cd $GITHUB_WORKSPACE/Learning.Test && unzip learning.zip

      #- name: Download File
       # run: |
        #     curl -L -o $GITHUB_WORKSPACE/Learning.Test/learning.zip https://promactinfotech1-my.sharepoint.com/:u:/g/personal/rahmatali_promactinfo_com/EVSKuEdPTUdBpvg3eQNNr0QB7SbP4GyemsYT9VRDJ926ew?e=yCfnNP
         #    ls -R $GITHUB_WORKSPACE/Learning.Test
             
      #- name: Unzip File
       # run: |
        #    unzip -d $GITHUB_WORKSPACE/Learning.Test learning.zip

      #- name: Show Downloaded File
       # run: |
          #ls -al $GITHUB_WORKSPACE   # List files in the Learning.Test directory
          # Add any other commands to verify or manipulate the downloaded file
      - name: Run tests
        run: |
          dotnet tool install dotnet-coverage
          dotnet tool run dotnet-coverage collect -f cobertura -o Learning.Test.cobertura.xml dotnet test
          dotnet tool run dotnet-coverage merge --remove-input-files -o ${{github.workspace}}/coverage.xml -f cobertura -r *.cobertura.xml

      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        #with:
         # token: ${{ secrets.CODECOV_TOKEN }}
          #directory: ${{ github.workspace }}
          #files: ./coverage.xml
          #flags: unittests
          #name: codecov-learning
          #fail_ci_if_error: true
          #verbose: true
