name: Test and Build .NET Project with SQLite

on: [push] # Trigger the workflow on push events

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - uses: actions/checkout@v3 # Checkout the repository code

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x" # Specify the desired .NET version

      - name: Install SQLite
        run: sudo apt-get install sqlite3

      - name: Install NuGet dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run tests
        run: |
          dotnet tool install dotnet-coverage
          dotnet tool run dotnet-coverage collect -f cobertura -o Sentra.Test.cobertura.xml dotnet test ./Learning.Test/Learning.Test.csproj
          dotnet tool run dotnet-coverage merge --remove-input-files -o ${{github.workspace}}/coverage.xml -f cobertura -r *.cobertura.xml        
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos 
          directory: ${{github.workspace}}
          files: ./coverage.xml # optional
          flags: unittests # optional
          name: codecov-theraparea # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
