name: SQL Server Testing with Docker

on: [push, pull_request]  # Trigger the workflow on pushes or pull requests

jobs:
  test_with_sql_server:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Check out the repository code

      - name: Start SQL Server container
        uses: docker://mcr.microsoft.com/mssql/server:2019-latest  # Use the SQL Server 2019 container
        with:
          ACCEPT_EULA: Y  # Accept the End-User License Agreement
          SA_PASSWORD: ${{ secrets.SA_PASSWORD }}  # Set the SQL Server password from a secret
          PORTS: 1433  # Expose the SQL Server port

      - name: Install testing dependencies
        run: |
          dotnet tool install --global tSQLt  # Install tSQLt for testing
          # Install any other required testing tools or frameworks here

      - name: Run tests
        run: |
          tSQLt.cmd run  # Execute tSQLt tests against the containerized database
          # Add any other commands to run additional tests here

      - name: Report results (optional)
        uses: actions/upload-artifact@v3  # Upload test results as artifacts
        with:
          name: test-results
          path: results/*
