name: SQL Server Setup
on:
  push:
    branches:
      - master

jobs:
  setup-sql-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SQL Server
        uses: 280780363/sqlserver-action@v1.0
        with:
          accept-eula: true
          server-name: localhost
          instance-name: SQLExpress
          sa-password: "Post@123"
          admin-password: "Post@123" #${{ secrets.SQL_ADMIN_PASSWORD }}
          config-only: false

      - name: Build and Deploy Database
        run: |
          dotnet build
          dotnet test --configuration Release --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
        env:
          SQL_SERVER_CONNECTION_STRING: "Server=localhost\SQLExpress;Database=learning;User Id=sa;Password=Post@123;"

      # Add additional steps as needed for your specific setup
