name: SQL Server Testing with Docker on Windows

on:
  push:
    branches:
      - master

jobs:
  test_with_sql_server:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start SQL Server container
        uses: docker://mcr.microsoft.com/mssql/server:2019-latest
        with:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SQL_SERVER_SA_PASSWORD }}
          PORTS: 1433

      - name: Install testing dependencies (Windows-specific commands)
        run: choco install tSQLt.cmd  # Example for tSQLt on Windows

      - name: Run tests
        run: tSQLt.cmd run  # Execute tSQLt tests against the containerized database

      - name: Report results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/*
