name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    env:
      CONNECTION_STRING: ${{ secrets.SQL_SERVER_CONNECTION_STRING }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'  # Adjust as needed

    - name: Build and Test
      run: |
        dotnet build
        dotnet test

    #- name: Setup SQL Server
      #run: |
        # Your SQL Server setup commands here
        # Create and initialize the temporary database

    #- name: Run Tests with SQL Server
     # run: |
        # Run tests that interact with SQL Server
