name: Docker Build and Test
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server
        env:
          SA_PASSWORD: Post@123!
          ACCEPT_EULA: Y
          MSSQL_DATABASE: TestDb
        ports:
          - "1433:1433"
        options: --health-cmd="sqlcmd -S localhost -U sa -P Post@123! -d master -Q \"SELECT 1\"" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    #- name: Build and Test
     # run: |
      #  dotnet build
       # dotnet test

    - name: Cleanup
      run: |
        # You can add cleanup steps here if needed
