name: Forest CI

on:
  push:
  
jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server
        env:
          SA_PASSWORD: ${{ secrets.SQL_SERVER_SA_PASSWORD }}
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
        options: >-
          --health-cmd="sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install packages
        run: dotnet restore

      - name: Setup Database
        env:
          SA_PASSWORD: ${{ secrets.SQL_SERVER_SA_PASSWORD }}
        run: "dotnet ef database update"  # Replace with your Entity Framework migration command

      - name: Run Tests
        run: dotnet test
